version: '3.1'

services:

  db:
    container_name: 'postgresdb'
    image: "postgres:13"
    restart: always
    environment:
      POSTGRES_USER: hacku
      POSTGRES_PASSWORD: passwordofMyDb-24
      POSTGRES_DB: monitordb
    ports:
      - 4321:5432
    volumes:
      - data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  migrations:
    container_name: "migrations"
    build: .
    depends_on: 
      - db
    command: bash -c "node migrate.js"

  api:
    container_name: "api"
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on: 
      - db
      - migrations
      - worker
    command: bash -c "node app.js"


  worker:
    container_name: "worker"
    build: .
    restart: always
    depends_on:
      - db
    command: bash -c "node worker.js"

volumes:
  data: